// frontend-angular/src/app/dashboard/dashboard-card/dashboard-card.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-dashboard-card",
  templateUrl: "./dashboard-card.component.html",
  styleUrls: ["./dashboard-card.component.scss"]
})
export class DashboardCardComponent {
  @Input() public name: string;
  @Input() public spend: number;
}

<app-card [title]="name" subTitle="Spending in March 2015">
  <p class="service-spending-value mat-display-1">{{spend | currency : 'GBP' }}</p>
</app-card>

// frontend-react/src/dashboard/dashboard-card/DashboardCard.tsx
import React from 'react';
import './DashboardCard.css';
import Card from "../../shared/layout/card/Card";
import Currency from "../../shared/formatting/Currency";
import { ServiceSpend } from "../ServiceSpend";

function DashboardCard({ service, spending }: ServiceSpend) {
  return (
    <Card title={service} subtitle="Spending in March 2015">
      <div className="Dashboard-card-content">
        <h2 className="Card-value">
          <Currency value={spending} currency="£"/>
        </h2>
      </div>
    </Card>
  )
}

export default DashboardCard;
